const level_info = [
    {
        level: 0,
        name: "Normal Text",
        prompt: "Normal Text",
        message: `Welcome to the \`learn-markdown-game\`! Markdown is commonly used in \`README.md\`, Jupyter notebooks, and various other places. There are several levels to this tutorial and a few checkpoints, and by the end you'll be a master of Markdown!\n\nIn this example, you'll learn the easiest thing in Markdown: **normal text**.\n\nType text in the middle panel to see it rendered in the right panel. Your goal is to recreate what's in the left panel.`,
    },
    {
        level: 1,
        name: "Heading 1",
        prompt: "# Heading 1",
        message: `To create a heading, use a \`#\` followed by a space, then your heading text.\n\`# This is my heading\``,
    },
    {
        level: 2,
        name: "Horizontal Rule",
        prompt: "---",
        message: `Create a horizontal rule by typing three dashes (\`---\`) on a new line. Horizontal rules are useful for separating sections of your document.`,
    },
    {
        level: 3,
        name: "Checkpoint 1",
        prompt: `# Heading 1\n\n---\n\nNormal Text.`,
        message: `**Checkpoint**: Combine a heading, horizontal rule, and normal text into a single document.`,
    },
    {
        level: 4,
        name: "Italics",
        prompt: "*Italics*",
        message: `Create *italic text* by adding a single asterisk on both sides of your text.\n\`*italic text*\``,
    },
    {
        level: 5,
        name: "Bold",
        prompt: "**Bold**",
        message: `Create **bold text** by adding double asterisks on both sides of your text.\n\`**bold text**\``,
    },
    {
        level: 6,
        name: "Strikethrough",
        prompt: "~~strikethrough~~",
        message: "Strikethrough this text using double tildes. (`~~strikethrough~~`)",
    },
    {
        level: 7,
        name: "Checkpoint 2",
        prompt: `*Italic*\n\n**Bold**\n\n~~Strikethrough~~`,
        message: `**Checkpoint**: Combine italic, bold, and strikethrough formatting into a single document.`,
    },
    {
        level: 8,
        name: "Bold and Italics",
        prompt: "***Bold and Italics***",
        message: `To create text that's both bold and italic, use three asterisks on both sides of your text. (\`***Bold and Italics***\`)`,
    },
    {
        level: 9,
        name: "Inline Code",
        prompt: "`Inline Code`",
        message: "To create inline code, use a single backtick on both sides of your text. (\`inline code\`)",
    },
    {
        level: 10,
        name: "Code Block",
        prompt: "``````",
        message: `To create a block of code, use triple backticks:\n\n\`\`\`\nYour code here\n\`\`\``,
    },
    {
        level: 11,
        name: "Blockquote",
        prompt: `> This is a blockquote.`,
        message: `Use the greater-than sign (\`>\`) to create blockquotes:\n\n\`> Quote\``,
    },
    {
        level: 12,
        name: "Checkpoint 3",
        prompt: `***Bold and Italics***\n\n\`Inline Code\`\n\n\`\`\`\nCode Block\n\`\`\`\n\n> Blockquote`,
        message: `**Checkpoint**: Combine bold and italics, inline code, code block, and blockquote formatting into a single document.`,
    },
    {
        level: 13,
        name: "All Headings",
        prompt: `# Heading 1\n## Heading 2\n### Heading 3\n#### Heading 4\n##### Heading 5\n###### Heading 6`,
        message: `Markdown has 6 levels of headings. Heading 1 is the biggest, and Heading 6 is the smallest.\nHeading 1 is followed by 1 hash (\`#\`), Heading 2 by 2 hashes, and so on.`,
    },
    {
        level: 14,
        name: "Unordered List",
        prompt: `- Item 1\n- Item 2\n- Item 3`,
        message: `For unordered lists, use dashes, asterisks, or plus signs:\n\n\`- Item\``,
    },
    {
        level: 15,
        name: "Ordered List",
        prompt: `1. Item 1\n2. Item 2\n3. Item 3`,
        message: `Create ordered lists using numbers followed by a period:\n\n\`1. Item\``,
    },
    {
        level: 16,
        name: "Checkpoint 4",
        prompt: `# Main Heading\n\n## Subheading\n\n- Unordered item 1\n- Unordered item 2\n\n1. Ordered item 1\n2. Ordered item 2`,
        message: `**Checkpoint**: Combine headings, unordered list, and ordered list into a single document.`,
    },
    {
        level: 17,
        name: "Nested Lists",
        prompt: "- Item 1\n  - Subitem 1\n  - Subitem 2\n- Item 2",
        message: "Create a nested list with subitems.",
    },
    {
        level: 18,
        name: "Task List",
        prompt: "- [x] Task 1\n- [ ] Task 2\n- [ ] Task 3",
        message: "Create a task list with one completed task and two pending tasks.",
    },
    {
        level: 19,
        name: "Table",
        prompt: `| Header 1 | Header 2 |\n|----------|----------|\n| Row 1   | Data 1   |\n| Row 2   | Data 2   |`,
        message: `Tables are created using pipes (\`|\`) and dashes (\`-\`).\n\n\`\`\`\n| Header 1 | Header 2 |\n|---------|----------|\n| Row 1   | Data 1   |\n| Row 2   | Data 2   |\n\`\`\``,
    },
    {
        level: 20,
        name: "Checkpoint 5",
        prompt: `- Nested List\n  - Subitem 1\n  - Subitem 2\n\n- [ ] Pending Task\n- [x] Completed Task\n\n| Column 1 | Column 2 |\n|----------|----------|\n| Data 1   | Data 2   |`,
        message: `**Checkpoint**: Combine nested list, task list, and table into a single document.`,
    },
    {
        level: 21,
        name: "Link",
        prompt: `[Link Text](https://example.com)`,
        message: `Create links with the syntax:\n\n\`[Link Text](URL)\`\n\nYou can make the Link point anywhere you want, but may I suggest \`learn-markdown-game.com\`?`,
    },
    {
        level: 22,
        name: "Image",
        prompt: `![Alt text](cat.jpg)`,
        message: `Embed images using this syntax:\n\n\`![Alt text](URL)\`\n\nDisplay the image \`cat.jpg\``,
    },
    {
        level: 23,
        name: "YouTube Video",
        prompt: `[![Alt text](https://img.youtube.com/vi/video-id/0.jpg)](https://www.youtube.com/watch?v=video-id)`,
        message: `To embed a YouTube video as a link, use the following syntax:\n\n\`[![Alt text](https://img.youtube.com/vi/video-id/0.jpg)](https://www.youtube.com/watch?v=video-id)\``,
    },
    {
        level: 24,
        name: "Disabling Markdown",
        prompt: "\\*This will not be italic\\*",
        message: `You can disable Markdown formatting by escaping characters using a backslash (\\):\n\n\`\\*Not Italic\\*\``,
    },
    {
        level: 25,
        name: "Checkpoint 6",
        prompt: `[Visit our website](https://example.com)\n\n![Cute cat](cat.jpg)\n\n[![Funny video](https://img.youtube.com/vi/dQw4w9WgXcQ/0.jpg)](https://www.youtube.com/watch?v=dQw4w9WgXcQ)\n\n\\*\\*This is not bold\\*\\*`,
        message: `**Checkpoint**: Combine link, image, YouTube video embed, and escaped Markdown into a single document.`,
    },
    {
        level: 26,
        name: "Final Checkpoint",
        prompt: `# Markdown Mastery\n\n## Demonstration of Skills\n\n### Text Formatting\n\n*Italic*, **bold**, and ***bold italic*** text.\n\n### Lists\n\n- Unordered list item 1\n- Unordered list item 2\n  - Nested item\n\n1. Ordered list item 1\n2. Ordered list item 2\n\n### Task List\n\n- [x] Completed task\n- [ ] Pending task\n\n### Code\n\nInline \`code\` and a code block:\n\n\`\`\`python\nprint("Hello, Markdown!")\n\`\`\`\n\n### Blockquote\n\n> This is a blockquote.\n\n### Table\n\n| Header 1 | Header 2 |\n|----------|----------|\n| Row 1    | Data 1   |\n| Row 2    | Data 2   |\n\n### Links and Images\n\n[Visit our website](https://example.com)\n\n![Cute cat](cat.jpg)\n\n### Escaped Characters\n\n\\*This is not italic\\*\n\n---\n\nCongratulations on completing the Markdown tutorial!`,
        message: `This is the final checkpoint. Show off everything you've learned in Markdown!`,
    },
];

export default level_info;
